jobs:
  - job: Test
    pool:
      vmImage: "macOS 10.13"
    trigger:
      branches:
        include:
          - develop
    steps:
    - template: build-and-test/build-and-test.yml
      parameters:
        branch: feature/azure
